//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPruebaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int ID { get; set; }
        public string Nom_jugador { get; set; }
        public string Dorsal { get; set; }
        public string fnac { get; set; }
    }
}
