//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobreEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clas
    {
        public Clas()
        {
            this.Alumnos = new HashSet<Alumno>();
        }
    
        public int ID { get; set; }
        public string Curso { get; set; }
    
        public virtual ICollection<Alumno> Alumnos { get; set; }
    }
}
